Show unrestricted scopes into well-known endpoint
indigo-iam/iam pull request #628
Opened 2023-07-10 13:56 UTC by federicaagostini

When an admin adds a new System Scope, if it is unrestricted it should appear in the well-known endpoint.

Right now just default scopes were published.

2023-07-12 10:14 UTC, giacomini commented on iam-login-service/src/main/java/it/infn/mw/iam/config/CacheConfig.java
> +    Cache getCacheForWellKnown = cacheManager.getCache(IamWellKnownInfoProvider.CACHE_KEY);
`cacheForWellKnown` (w/o get)

2023-07-21 13:19 UTC, enricovianello requested changes

2023-07-21 13:19 UTC, enricovianello commented on iam-login-service/src/main/java/it/infn/mw/iam/config/CacheConfig.java
> +
Move this code to it.infn.mw.iam.config.TaskConfig

2024-04-10 10:24 UTC, enricovianello approved these changes

2024-04-10 10:25 UTC, merged