Store user affiliation into user info table
indigo-iam/iam pull request #781
Opened 2024-06-05 15:08 UTC by garaimanoj

User registration page 
![image](https://github.com/user-attachments/assets/0ffd0f6e-036f-4cdd-af8e-623eee0ae622)

User details view for Admin
![image](https://github.com/user-attachments/assets/0f3de15b-1987-4169-8e68-a8185d907087)

User details edit page for Admin
![image](https://github.com/user-attachments/assets/f03df1f6-f0d6-4717-b0fe-9eff4bacf73e)

Response of SCIM REST api call
![image](https://github.com/user-attachments/assets/703b24c6-d46a-4833-ac48-39e0e4f0b482)

2025-06-18 10:33 UTC, enricovianello requested changes
I think we can assign less than 4096 characters to this column. e.g. 200 should be enough.

2025-06-18 10:33 UTC, enricovianello commented on iam-persistence/src/main/java/it/infn/mw/iam/persistence/model/IamUserInfo.java
> +  @Column(length = 4096)
we're expecting this value as a University or Institute name so having 4096 characters for this value is, in my opinion, too much. I think 200 should be greater enough to fit what we need. What do you think?

2025-06-18 10:54 UTC, garaimanoj commented on iam-persistence/src/main/java/it/infn/mw/iam/persistence/model/IamUserInfo.java
> +  @Column(length = 4096)
Updated to 200

2025-06-20 12:50 UTC, enricovianello approved these changes

2025-06-20 13:46 UTC, enricovianello commented
We must include a notice in the release notes that says: "If Affiliation is not included into your privacy notice, then it must be updated after/during IAM update"

2025-07-03 15:55 UTC, enricovianello approved these changes

2025-07-03 15:56 UTC, merged