Assign oidc-agent clients to whom approved it
indigo-iam/iam pull request #817
Opened 2024-07-25 09:52 UTC by enricovianello

2024-08-01 15:53 UTC, rmiccoli requested changes
The test that fails is due to a constraint on a column of a mysql table (not h2). Consider correcting/eliminating the test if not necessary

2024-08-02 10:33 UTC, federicaagostini commented
> The test that fails is due to a constraint on a column of a mysql table (not h2). Consider correcting/eliminating the test if not necessary

Test removed, as it will never be reproducible in production due to mysql constraint.

2024-08-02 10:58 UTC, rmiccoli approved these changes

2024-08-07 08:47 UTC, federicaagostini commented
Superseded by https://github.com/indigo-iam/iam/pull/821

2024-08-07 08:47 UTC, closed without merging